### ISSUE TITLE
youtube not working

### ISSUE THREAD

**Issue by easella** [BinBashBanana/pywb-test#11]
This proxy does not work with recaptcha, so i can't view youtube

![image](https://user-images.githubusercontent.com/74786054/112709503-9d465880-8e90-11eb-9baf-98a5d9c5ea97.png)

**Comment by BinBashBanana** [comment]
Damn, I gotta fix this soon.

**Comment by easella** [comment]
it does not navigate to that screen most of the time. Only once in a while does it do the are you s robot thing.
