### ISSUE TITLE
netflix not working

### ISSUE THREAD

**Issue by easella** [BinBashBanana/pywb-test#13]
![image](https://user-images.githubusercontent.com/74786054/115099656-51258b80-9f05-11eb-94d0-fe8a4de792a6.png)
video does not even load.
![image](https://user-images.githubusercontent.com/74786054/115100012-ca25e280-9f07-11eb-96c7-9e20f8578b83.png)

**Comment by BinBashBanana** [comment]
no. we're done here. do not open any more issues

**Comment by BinBashBanana** [comment]
also, do not use the demo listed on the repository page. make your own if you want to.

**Comment by easella** [comment]
can you please fix it though?
