### ISSUE TITLE
Hosting on windows 10?

### ISSUE THREAD

**Issue by cannonbruno** [BinBashBanana/pywb-test#14]
Is it possible to host on windows 10? 

`pip install -r requirements.txt` cannot find a matching distribution for uwsgi
`sudo python setup.py install` says i do not have access to directory  (yes I have run console as admin)

Using either cmd or powershell does not make a difference

**Comment by BinBashBanana** [comment]
Try using `pip3` instead of `pip` and `python3` instead of `python` in the command.

**Comment by cannonbruno** [comment]
I still get both of the previous errors. I will try re-installing python real quick. Any other suggestions?

**Comment by cannonbruno** [comment]
A fresh install of python didn't work. It appears that my WindowsApps folder is denying permission no matter what happens. I am an administrator on this PC but it completely ignores that and denies my permission to read or write.

**Comment by BinBashBanana** [comment]
Are you on administrator: command prompt?

**Comment by cannonbruno** [comment]
I am

**Comment by BinBashBanana** [comment]
Ok, all I can suggest is using WSL. That's what I use it on.

**Comment by cannonbruno** [comment]
WSL requires joining Windows Insider Program correct?

**Comment by BinBashBanana** [comment]
No? I don't think so.

**Comment by cannonbruno** [comment]
Could you clarify what WSL is?

**Comment by BinBashBanana** [comment]
Windows Subsystem for Linux (allows you to run bash shell on windows)

**Comment by BinBashBanana** [comment]
If you look on Microsoft's website, it they have some good articles on how to set it up. You'll also want to upgrade to WSL 2, it isn't necessary but I'd recommend it.
