### ISSUE TITLE
ReCaptcha Support

### ISSUE THREAD

**Issue by dontlikeya-lol** [BinBashBanana/pywb-test#16]
It will be greatly appreciated if you were to work on adding reCAPTCHA and hCAPTCHA support. Many users want to use services like "Pinterest" and "Discord", but that requires captcha verification services.

**Comment by BinBashBanana** [comment]
top priority 👍

**Comment by easella** [comment]
this proxy works for recaptchas simply sitting in the background, but doesnt work for recaptcha challenges

**Comment by dontlikeya-lol** [comment]
dont even say that, just let him fix the first issue then you can tell him that

**Comment by easella** [comment]
also, instagram doesnt work

**Comment by BinBashBanana** [comment]
fuck instagram

**Comment by easella** [comment]
can you fix this in your next branch?

**Comment by easella** [comment]
d

**Comment by dontlikeya-lol** [comment]
I just wanted to say that **easella** is a person known for bothering people with questions and occasionally lying about things that are far from the truth. Instagram works exceptionally well -- I don't understand why she would say it doesn't work. 

Anywho, thank you for being aware of the current reCAPTCHA issue and responding so quickly.

**Comment by BinBashBanana** [comment]
OH DON'T GET ME STARTED ON EASELLA

**Comment by dontlikeya-lol** [comment]
LMAOOOO

**Comment by easella** [comment]
ok fine

**Comment by easella** [comment]
it doesnt work for logging in

**Comment by easella** [comment]
and im a boy!lmao
thats simply my yahoo email

**Comment by easella** [comment]
i dont lie
instagram doesnt let you login
![image](https://user-images.githubusercontent.com/74786054/119372932-e135be00-bc85-11eb-9d14-ceda4476a8e5.png)

**Comment by easella** [comment]
sorry 4 bothering u

**Comment by dontlikeya-lol** [comment]
it works; you just need to redeploy the proxy

**Comment by easella** [comment]
i cant. its not my proxy

**Comment by easella** [comment]
its the heroku demo that binbashbanana made

**Comment by easella** [comment]
im a he!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! AAAAAAAAAAAAAHHHHHHHHHHHHH! LMAO!!!!!!!!!!!!!!!!!!!

**Comment by BinBashBanana** [comment]
Please keep this issue on-topic.

**Comment by easella** [comment]
ok

**Comment by MatrixMMOfficial** [comment]
> I just wanted to say that **easella** is a person known for bothering people with questions and occasionally lying about things that are far from the truth. Instagram works exceptionally well -- I don't understand why she would say it doesn't work.
> 
> Anywho, thank you for being aware of the current reCAPTCHA issue and responding so quickly.
Sorry for the necropost, but going back to the instagram topic I have encountered a issue with instagram DMS. They stay greyed out in a blank state when you go to the DM page.
Sorry for being somewhat informal.
Screenshot below.

**Comment by dontlikeya-lol** [comment]
Did you finally add reCAPTCHA support?

**Comment by vackyton** [comment]
Lol @easella has be commenting so much advertising her/his site to get the links but you can just press ctrl+u to get the password and also she/he has been commenting so much on the holyub github and bothering others too lol
