### ISSUE TITLE
Instagram DM Unreliability

### ISSUE THREAD

**Issue by walkthestars** [BinBashBanana/pywb-test#17]
Hello, I'd like to start out by saying this is the only working proxy that managed to get instagram DM's working.
At least it was.
I went to the DM's list, messaged a friend, went off the site to go do something, came back, and now the DM's list is just greyed out.
Using a heroku app deployed version of the PyDodge proxy.
Screenshot of my issue below.
![Screenshot 2021-06-17 3 48 39 PM](https://user-images.githubusercontent.com/64265241/122463647-d9ff8880-cf83-11eb-99b4-59bd37ab1d64.png)

**Comment by BinBashBanana** [comment]
Hey, this proxy is kinda dead right now, I would recommend using womginx.

**Comment by walkthestars** [comment]
Yeah about that, Already tried womginx. Got it working with discord but instagram with it just refreshes endlessly.
thanks for the fast reply also, its' rare to have that kind of a quick response.

**Comment by walkthestars** [comment]
Ok. Deploying a new proxy fixes the issue, thats odd. I will see if it returns if i exit the page.

**Comment by walkthestars** [comment]
Still there. I suppose this solved for now i guess. Ill reopen (if i can, new to github lol) or do whatever needed.

**Comment by BinBashBanana** [comment]
Weird... maybe one of the updates fixed it and the heroku app didn't have it yet.

**Comment by walkthestars** [comment]
well, i deployed both today, so thats doubtful.

**Comment by walkthestars** [comment]
Yep its broken again

**Comment by walkthestars** [comment]
could you point me in the direction of a proxy that does have instagram working?

**Comment by BinBashBanana** [comment]
I don't know if this will work, but you can try it. https://github.com/titaniumnetwork-dev/alloy

**Comment by walkthestars** [comment]
tried already, sadly. 
alloy also has the same grey screen issue

**Comment by BinBashBanana** [comment]
I'm sorry I couldn't help you.

**Comment by walkthestars** [comment]
Its fine. You tried, thats more then I can say for most.
Thank you.

**Comment by walkthestars** [comment]
Have a good day/night.
