### ISSUE TITLE
OH DON'T GET ME STARTED ON EASELLA

### ISSUE THREAD

**Issue by nevr13** [BinBashBanana/pywb-test#18]
OH DON'T GET ME STARTED ON EASELLA

_Originally posted by @BinBashBanana in https://github.com/BinBashBanana/PyDodge/issues/16#issuecomment-846349327_

proxy not working, help   {dumb screenshot here with no details blurred out} it no work!??!?!?!?!11!?!?!?! pls help in no work. and this is the day of the life of easella.

**Comment by BinBashBanana** [comment]
wha
