### ISSUE TITLE
Install on Ubuntu VPS

### ISSUE THREAD

**Issue by ingnelson** [BinBashBanana/pywb-test#2]
Hello sir .
Can you give the command or a script to install it on a UBUNTU VPS , please ? 

I want to use my own domain too.

I will wait your answer.

**Comment by BinBashBanana** [comment]
First time:
1.  `pip install -r requirements.txt`
2. `setup.py install`

Running from then on:
1.  `uwsgi uwsgi.ini`

Please note that I will be adding virtualenv support for multiple domains on https soon, you may want to wait a few more days for me to get that figured out.

**Comment by ingnelson** [comment]
@BinBashBanana I will wait sir.
If it is possible create a script  to clone and install it ; where we can only add the ip VPS or the domain .

Thanks

**Comment by BinBashBanana** [comment]
Oh uhh. I think I misinterpreted your question a while ago, but I hope I can still help:

Installation:
```bash
git clone https://github.com/BinBashBanana/PyDodge.git
cd PyDodge
pip3 install -r requirements.txt
python3 setup.py install
```
Running:
```bash
bash run.sh
```
