### ISSUE TITLE
"Application Error" when deploying to Heroku

### ISSUE THREAD

**Issue by ghost** [BinBashBanana/pywb-test#21]
For some reason whenever I deploy PyDodge it gives out this application error. After, I even tried creating a runtime file to change Python's version but that doesn't even work..
![](https://i.stack.imgur.com/Gid2R.png)

**Comment by BinBashBanana** [comment]
Can you send the application logs?

**Comment by ghost** [comment]
The log is never ending - it constantly attempts to "respond worker 1"

I do not know if this has to do anything with deployment error - when ever I try to use the button "deploy to heroku" it fails, and this message is shown: "Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy." 
... 
To bypass this, basically I just created a empty app and then later connecting my Github account to upload the proxy. I don't know if it's blocking any files?

**Comment by ghost** [comment]
I also notice that when deploying Heroku says that no Python version is detected so it automatically uses 3.10.3. Does the code support this version? Is there a certain version of Python I should be using for PyDodge? Or more over does Python 3.10.3 support all of the requirements in https://github.com/BinBashBanana/PyDodge/blob/master/requirements.txt?

**Comment by BinBashBanana** [comment]
> "Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."
There's nothing I can do about this, the easiest way to get around it is to just fork the repository and deploy the fork.

I can't find anything in the logs, possibly try an older version of python (3.6 or 3.7)

Really what you should do is consider an alternative such as [Ultraviolet](https://github.com/titaniumnetwork-dev/Ultraviolet), as pydodge is pretty outdated.

**Comment by ghost** [comment]
I used an older version of python-3.7.13, and now got the generic "Internal Server Error".  Can you happen to find anything in this new logs?
[murmuring-oasis-34315-logs-1648271498060.txt](https://github.com/BinBashBanana/PyDodge/files/8354705/murmuring-oasis-34315-logs-1648271498060.txt)

(I created a txt file named runtime and wrote python-3.7.13 to declare that version.) Here's [a list](https://devcenter.heroku.com/articles/python-support) of Heroku's so-called supported python supported versions.

**Comment by ghost** [comment]
[Here's the heroku link.](https://murmuring-oasis-34315.herokuapp.com/)

**Comment by ghost** [comment]
This is @queasydoughnuts, I just hopped accounts ... Heroku blocked my other github account, so I use this one to upload things to Heroku's server

**Comment by BinBashBanana** [comment]
Strange... it looks like it wasn't able to detect the application this time. Try running `bash run-heroku.sh` in the console.

**Comment by ghost** [comment]
here's what the console outputted:

[uWSGI] getting INI configuration from uwsgi-heroku.ini
*** Starting uWSGI 2.0.20 (64bit) on [Sat Mar 26 05:26:12 2022] ***
compiled with version: 9.4.0 on 26 March 2022 05:08:51
os: Linux-4.4.0-1101-aws #106-Ubuntu SMP Tue Mar 1 10:51:49 UTC 2022
nodename: fcc9c596-a595-42f5-a785-e049f120ebbe
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /app
detected binary path: /app/.heroku/python/bin/uwsgi
your processes number limit is 256
your memory page size is 4096 bytes
detected max file descriptor number: 10000
- async cores set to 100 - fd table size: 10000
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :38512 fd 3
Python version: 3.7.13 (default, Mar 16 2022, 21:15:28)  [GCC 9.4.0]
Python main interpreter initialized at 0x559f9ea096b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 2216128 bytes (2164 KB) for 100 cores
*** Operational MODE: async ***
Traceback (most recent call last):
  File "./pywb/apps/wayback.py", line 2, in <module>
    from pywb.apps.frontendapp import FrontEndApp
  File "./pywb/apps/frontendapp.py", line 23, in <module>
    from pywb.rewrite.templateview import BaseInsertView
  File "./pywb/rewrite/templateview.py", line 8, in <module>
    from jinja2 import Environment, TemplateNotFound, contextfunction, select_autoescape
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/app/.heroku/python/lib/python3.7/site-packages/markupsafe/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 12, cores: 100)
*** running gevent loop engine [addr:0x559f9db44d50] ***

**Comment by BinBashBanana** [comment]
Looks like there were missing dependencies. Try `pip install -r requirements.txt` and then `bash run-heroku.sh`

**Comment by ghost** [comment]
Unfortunately still getting a 500 error, and here is my log now:


[murmuring-oasis-34315-logs-1648273615738.txt](https://github.com/BinBashBanana/PyDodge/files/8354764/murmuring-oasis-34315-logs-1648273615738.txt)

here's the console:

[uWSGI] getting INI configuration from uwsgi-heroku.ini
*** Starting uWSGI 2.0.20 (64bit) on [Sat Mar 26 05:44:13 2022] ***
compiled with version: 9.4.0 on 26 March 2022 05:08:51
os: Linux-4.4.0-1101-aws #106-Ubuntu SMP Tue Mar 1 10:51:49 UTC 2022
nodename: 48864397-4bba-40da-93fa-64d10e1a95f4
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /app
detected binary path: /app/.heroku/python/bin/uwsgi
your processes number limit is 256
your memory page size is 4096 bytes
detected max file descriptor number: 10000
- async cores set to 100 - fd table size: 10000
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :28011 fd 3
Python version: 3.7.13 (default, Mar 16 2022, 21:15:28)  [GCC 9.4.0]
Python main interpreter initialized at 0x559bb4ab56b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 2216128 bytes (2164 KB) for 100 cores
*** Operational MODE: async ***
Traceback (most recent call last):
  File "./pywb/apps/wayback.py", line 2, in <module>
    from pywb.apps.frontendapp import FrontEndApp
  File "./pywb/apps/frontendapp.py", line 23, in <module>
    from pywb.rewrite.templateview import BaseInsertView
  File "./pywb/rewrite/templateview.py", line 8, in <module>
    from jinja2 import Environment, TemplateNotFound, contextfunction, select_autoescape
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/.heroku/python/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/app/.heroku/python/lib/python3.7/site-packages/markupsafe/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 12, cores: 100)
*** running gevent loop engine [addr:0x559bb2f7ed50] ***

**Comment by ghost** [comment]
Well my heroku account just got banned so I'm unfortunately this whole process has gone to waste
