### ISSUE TITLE
Heroku deploying issue fixed (of 4/2/22)

### ISSUE THREAD

**Issue by ghost** [BinBashBanana/pywb-test#23]
Hi BinBashBanana,

After lots of research with the requirements I finally figured out how to make PyDodge available to Heroku.
On my fork, I created a file called runtime.txt. It took me long time to figure out which Python version was supported, it's 3.6.15. Here's the file: 

[runtime.txt](https://github.com/BinBashBanana/PyDodge/files/8403375/runtime.txt)

So that means that Heroku supports PyDodge if it's on python-3.6.15. This version has reached it's end-of-life on Heroku, meaning it's going to be removed in the future. I **highly** recommend you update the code to support Heroku's latest Python verison, which is python-3.10.3. For now, I recommend you upload the runtime file to make PyDodge available for all users using Heroku!
 
[Consider reading this article.](https://devcenter.heroku.com/articles/python-support) 

Queasy Doughnuts

**Comment by ghost** [comment]
And yes, I've used other proxies such as UltraViolet, NodeProxy, Alloy, Corrosion, you name it. I've tried them all. PyDodge is the best. Why's that? It supports the most sites. Sure, some of the newer proxies support more advanced ones, but PyDodge supports more sites total.

I think you and your team should bring back PyDodge. Or, maybe completely rewrite it. Maybe create a new proxy with Python.

**Comment by queasydoughnuts** [comment]
Also, I figured I mention this. There's an error with Google, it constantly refreshes over and over again. Ih haven't seen this issue in the past.

[Here's a video.](https://user-images.githubusercontent.com/67052902/161401930-4b21898e-0997-4a56-bb77-f48b4828b5d7.mov)

**Comment by BinBashBanana** [comment]
I've added the runtime.txt you provided, thank you.

Remember that PyDodge is 100% [pywb](https://github.com/webrecorder/pywb) just with configuration changes and one change made to rewriterapp.py to make it compatible with heroku, etc. I won't be making any more proxies, probably ever.
