### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by easella** [BinBashBanana/pywb-test#6]
![image](https://user-images.githubusercontent.com/74786054/111179783-c575b380-8582-11eb-834f-e0c43e64a056.png)

**Comment by BinBashBanana** [comment]
the default prefix is `/course/`, not `/prefix/`

**Comment by easella** [comment]
blocked for security issues
![image](https://user-images.githubusercontent.com/74786054/111208939-c4a04a00-85a1-11eb-8cec-f980f3b7e432.png)

**Comment by BinBashBanana** [comment]
Not related to the repository, this just happens because web filters report the website. Deploy your own and this won't happen.
