### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by irhrhd** [BinBashBanana/pywb-test#7]
Does this website support discord and rechapcha

**Comment by irhrhd** [comment]
Never mind discord works

**Comment by irhrhd** [comment]
Maybe not reChapahca

**Comment by BinBashBanana** [comment]
no reCaptcha support yet

**Comment by irhrhd** [comment]
Could you use wombat?

**Comment by BinBashBanana** [comment]
wombat.js is already used
