### ISSUE TITLE
zombs io not working

### ISSUE THREAD

**Issue by easella** [BinBashBanana/pywb-test#8]
![image](https://user-images.githubusercontent.com/74786054/111919037-4d196180-8a5e-11eb-96af-7c447b4f92ba.png)

**Comment by BinBashBanana** [comment]
That's not even pydodge. That's womginx.

**Comment by BinBashBanana** [comment]
https://github.com/binary-person/womginx

**Comment by easella** [comment]
ok here is pydodge.
![image](https://user-images.githubusercontent.com/74786054/111919694-af279600-8a61-11eb-9ba2-efe30ab0ac8e.png)

**Comment by BinBashBanana** [comment]
ok it doesn't work. I may fix this later but for now, it will not be fixed.
